[package]
edition = "2018"
name = "rusb"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "1"
napi-derive = "1"
rusb = "0.9"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
